### ISSUE TITLE
How to get around "DoNotAllowAnythingOtherThanAboveUnlessMFA" AWS policy using S3-uploads

### ISSUE THREAD

**Issue by theasteve** [humanmade/S3-Uploads#321]
(feature request?) I'm currently using `s3-uploads` in order to upload some files to an S3 bucket. One of the road blocks is that my organization has a strict AWS policy of 
`"DoNotAllowAnythingOtherThanAboveUnlessMFA" `
So in order to make requests to the S3 bucket I need an MFA token. Currently the application only requests 

```
  S3_UPLOADS_BUCKET: 
  S3_UPLOADS_KEY: 
  S3_UPLOADS_SECRET: 
  S3_UPLOADS_REGION: 
```

Is there a suggestion on how create the MFA token requirement? (feature request)
